Tsyringe
Angelo-silva-warren/accelerate-everest-challenge-ts-main-master pull request #3
Opened 2022-07-06 17:20 UTC by Angelo-silva-warren

2022-07-06 17:48 UTC, ismaelalvesgit commented on src/domain/user/helper/UserHelper.ts
> +    // this.repository.getFilter('email')
Sugestão:
Remover trechos códigos que não estão sendo mais utilizado

2022-07-06 17:51 UTC, ismaelalvesgit commented
Sugestão:
Percebi que padrão de espaçamentos e pontuação não estão seguindo um padrão ao decorrer do código sugiro uso da lib [eslint](https://www.npmjs.com/package/eslint)

2022-07-06 19:15 UTC, ismaelalvesgit commented on src/domain/user/helper/UserHelper.ts
>      lista.forEach((lista) => {
Sugestão:

Acredito que fique mais simples a utilização do `includes`
```js
let data = ['teste@teste.com', 'warren@warren.com']

console.log(data.includes('warren@warren.com')) // true
```

2022-07-06 19:45 UTC, ismaelalvesgit commented
Um pequeno detalhe que percebi no decorrer do codigo e a falta de padronização de nomes de variaveis e metodos sugiro usar o padrão [lowerCamelCase](https://pt.wikipedia.org/wiki/CamelCase)

Ex: 
 - UserRepository.readall -> UserRepository.readAll
 - UserService.UserCreate -> UserService.UserCreate

2022-07-06 20:21 UTC, ghost commented on src/domain/user/helper/UserHelper.ts
> +  emailCheck (dados: string, Mock: Iuser[]) : boolean {
O que é dados?

2022-07-06 20:21 UTC, ghost commented on src/domain/user/helper/UserHelper.ts
> +  emailCheck (dados: string, Mock: Iuser[]) : boolean {
O que é Mock?

2022-07-06 20:21 UTC, ghost commented on src/domain/user/helper/UserHelper.ts
> +import Iuser from '../../../interface/UserTypes'
```suggestion
import IUser from '../../../interface/UserTypes'
```

2022-07-06 20:24 UTC, viniciusoliveira-warren commented on src/domain/user/helper/UserHelper.ts
> +    return true
Esse return nunca vai acontecer

2022-07-06 20:33 UTC, ghost commented on src/domain/user/services/UserCreateService.ts
> +import { IuserRepository } from '../../../interface/domain/Repository/RepositoryTypes'
```suggestion
import { IUserCreate } from '../../../interface/domain/services/UserCreateTypes'
import { IUtil } from '../../../interface/util/UtilTypes'
import { IHelper } from '../../../interface/domain/helper/HelperTypes'
import IUser from '../../../interface/UserTypes'
import { IUserRepository } from '../../../interface/domain/Repository/RepositoryTypes'
```

2022-07-06 20:35 UTC, ghost commented on src/domain/user/services/UserCreateService.ts
> +
Se não estamos validando retorno do método, por que eles retornam `boolean`?

2022-07-07 18:58 UTC, Angelo-silva-warren commented on src/domain/user/helper/UserHelper.ts
> +  emailCheck (dados: string, Mock: Iuser[]) : boolean {
O Mock agora seria a database, aonde fica salvo os usuários

2022-07-07 18:58 UTC, Angelo-silva-warren commented on src/domain/user/helper/UserHelper.ts
> +  emailCheck (dados: string, Mock: Iuser[]) : boolean {
dados seria o json que recebo do insomnia

2022-07-07 19:00 UTC, Angelo-silva-warren commented on src/domain/user/helper/UserHelper.ts
> +    return true
Mudei esse trecho você poderia dar uma olhada agora ?

2022-07-07 19:26 UTC, ismaelalvesgit commented on src/domain/user/Repository/UserRepository.ts
> +  readall () {
Acredito que aqui ficaria mais didatico `readAll`

2022-07-07 19:29 UTC, ismaelalvesgit commented on src/domain/user/services/UserCreateService.ts
> +  UserCreate (dados: IUser) {
Acredito ficaria mais padronizado com o resto dos metodos do projeto se nome fosse `userCreate`

2022-07-07 19:30 UTC, ismaelalvesgit commented on src/domain/user/services/UserListService.ts
> +  CreateList () {
Acredito ficaria mais padronizado com o resto dos metodos do projeto se nome fosse `createList`

2022-07-07 20:33 UTC, devjunioralveswarren requested changes

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/Repository/UserRepository.ts
> +export default class UserRepository {
Faltou a implementação da interface IUserRepository

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/Repository/UserRepository.ts
> +  create (entity : IUser) : void {
Ao criar o usuário o ideal é que retorne esse usuário criado, no caso tu deixou explicito na função que deve retornar void. Algum motivo para isso?

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserCreateService.ts
> +class UserService implements IUserCreate {
`export class` ou `export default class`
dessa forma não precisa exportar no final do arquivo, o ideal é que mantenha um padrão de nome de arquivo, variáveis, classes e interfaces

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserCreateService.ts
> +  UserCreate (dados: IUser) {
padronizar o nome de funções e declarar oque a função retorna

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserCreateService.ts
> +      this.userHelper.emailCheck(dados.email, this.userRepository.database)
o ideal é retornar um booleano do helper, captar esse booleano e fazer um throw aqui na service caso esse boolean for false

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserCreateService.ts
> +      return { code: 201, msg: 'usuario criado' }
a responsabilidade de retornar o status code é do controller, aqui voce deve retornar o resultado da requisição

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserCreateService.ts
> +      return { code: 422, msg: message }
em um catch na service voce pode estar lançando em algum logger, como não é o caso o ideal é lançar um erro aqui e não retornar o status code e a mensagem de erro

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserListService.ts
> +  CreateList () {
não entendi ao certo, é uma função de criação ou listagem, o bom seria uma função com o nome listUsers ou algo do gênero

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/domain/user/services/UserListService.ts
> +    const lista = this.userRepository.readall()
manter apenas um padrão para o nome de funções, no caso em alguns momentos etá usando lower camel case e em outros momentos não

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/interface/UserTypes.ts
> +export default IUser
manter a exportação direta `export default interface IUser`

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/interface/domain/controller/ListControllerTypes.ts
> +  list: (req: Request, res: Response) => Promise<void>
algum motivo para a listagem retornar void?

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/interface/domain/controller/UserControllerTypes.ts
> +  userService : IUserCreate
Em qual momento essa declaração é usada na classe controller?

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/interface/domain/helper/HelperTypes.ts
> +  emailCheck(dados: string, Mock: IUser[]): void
não acho apropriado usar o nome dados, em portugues e no plural, sendo que tu recebe uma string, manter um único idioma para nomear variáveis

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/interface/domain/services/UserCreateTypes.ts
> +  userHelper : IHelper
Qual o motivo dessas duas declarações na tipagem uma vez que não foi utilizada na classe? relembrando os princípios do solid, que uma classe não deve implementar uma interface a qual tem funções que você não irá utilizar

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/interface/domain/services/UserListTypes.ts
> +  userHelper : IHelper
Algum motivo para tipar esse atributo na interface?

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/presentation/Routes.ts
> +  userList : ListController
sugiro:
CreateUserController
ListUserController
lembrar sempre de padronizar as declarações

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/presentation/controllers/ListController.ts
> +  list = async (req: Request, res: Response) => {
manter o padrão na criação de funções, em alguns momentos arrow function em outros funções normais? o ideal é que o projeto como um todo tenha padrões

2022-07-07 20:33 UTC, devjunioralveswarren commented on src/presentation/controllers/UsersController.ts
> +  handle = async (req: Request, res: Response) => {
manter o padrão na criação de funções, em alguns momentos arrow function em outros funções normais? o ideal é que o projeto como um todo tenha padrões

2022-07-12 17:34 UTC, Angelo-silva-warren commented on src/presentation/controllers/UsersController.ts
> +  handle = async (req: Request, res: Response) => {
mas precisa ser uma arrow function para o this não se perder quando usado no UserRouter

2022-07-12 17:38 UTC, Angelo-silva-warren commented on src/interface/domain/controller/UserControllerTypes.ts
> +  userService : IUserCreate
Ele é usado aqui(UserController)

```
handle = async (req: Request, res: Response) : Promise<void> => {
    const dados = req.body

    const createUser = await this.userService.userCreate(dados)
    res.status(createUser.code).json(createUser.msg)
  }
```

2022-07-13 12:48 UTC, ismaelalvesgit commented on src/presentation/controllers/UsersController.ts
> +    const dados = req.body
Sugestão:

```ts
const data = req.body 
# ou
const { body } = req
```

2022-07-13 12:48 UTC, ismaelalvesgit commented on src/domain/user/services/UserListService.ts
> +    const lista = this.userRepository.readAll()
Sugestão:
```ts
return this.userRepository.readAll()
```
E Acho que um nome mais condincente com a funcionalidade do metodo seria `listAll`

2022-07-13 12:48 UTC, ismaelalvesgit commented on src/util/util.ts
> +  cpfCheck (dados: string): void {
Sugestão: 
```ts
cpfCheck (value: string): void {}
# ou 
cpfCheck (cpf: string): void {}
```

2022-07-18 12:18 UTC, ismaelalvesgit commented on src/domain/user/services/UserListService.ts
> +    const list = this.userRepository.readAll();
Sugestão:

```ts
return this.userRepository.readAll();
```

2022-07-18 12:19 UTC, ismaelalvesgit commented on src/presentation/controllers/UsersController.ts
> +    const createUser = this.userService.userCreate(body);
Sugestão:
```ts
const { msg } = this.userService.userCreate(body);
```

2022-07-18 12:20 UTC, ismaelalvesgit commented on src/presentation/Routes.ts
> +  async routes(): Promise<void> {
Acho que talvez não seja necessário o uso do `async`

2022-07-21 20:16 UTC, ismaelalvesgit approved these changes

2022-07-21 20:27 UTC, ismaelalvesgit commented
Aprovei aqui. porem sugiro futuramente que adote [path-mapping](https://blog.rocketseat.com.br/path-mapping-typescript/) para abreviamento de importação de arquivos.

Antes:
```ts
import IUserRepository from '../../../interface/domain/Repository/RepositoryTypes';
import IUser from '../../../interface/UserTypes';
```

Depois:
```ts
import IUserRepository from '@interface/domain/Repository/RepositoryTypes';
import IUser from '@interface/UserTypes';
```

2022-07-22 14:30 UTC, merged